services:

  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    restart: unless-stopped
    env_file:
      - .env
    environment:
      COLLECTIONS: "crowdsecurity/nginx crowdsecurity/http-cve"
      GID: "998"
      CUSTOM_HOSTNAME: "oscar-shareable"
    volumes:
      - crowdsec-db:/var/lib/crowdsec/data
      - ./crowdsec/acquis.yaml:/etc/crowdsec/acquis.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    expose:
      - "8080"
    networks:
      - internal

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel run
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./cloudflared/config.yml:/etc/cloudflared/config.yml:ro
    networks:
      - internal

  nginx:
    build:
      context: ./nginx
    image: oscar-nginx-crowdsec:local
    container_name: nginx-internal
    env_file:
      - .env
    environment:
      CROWDSEC_LAPI_URL: http://crowdsec:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
      - ./logs/nginx:/var/log/nginx
    expose:
      - "80"
      - "443"
    restart: unless-stopped
    depends_on:
      - crowdsec
    networks:
      - internal
  uploader:
    container_name: uploader-test
    build:
      context: ./secure-uploader
      args: 
        UID: 911
        GID: 911
    user: "911:911"
    expose:
      - "50710"
    env_file:
      - .env
    environment:
      HTTPS_PORT: 50710
      UPLOAD_UID: 911
      UPLOAD_GID: 911
      OSCAR_BASE_URL: http://oscar:3000
    volumes:
      - uploads:/app/data/uploads
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp
      - /run
      - /var/tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    depends_on:
      - oscar
      - nginx
      - cloudflared
      - crowdsec
    networks:
      - internal

  oscar:
    build:
      context: ./docker-oscar
    container_name: oscar-test
    restart: unless-stopped
    ports:
      - 127.0.0.1:3030:3000
    volumes:
      - /var/www/oscar-data:/config/Documents/OSCAR_Data:rw
      - uploads:/config/SDCARD:rw
    environment:
      PUID: "911"
      PGID: "911"
      TZ: "America/Chicago"
      TITLE: "OSCAR 1.7.0"
      START_DOCKER: "false"
      DISABLE_IPV6: "true"
      NO_DECOR: "true"
      NO_GAMEPAD: "true"
      HARDEN_DESKTOP: "true"
      HARDEN_OPENBOX: "true"
      SELKIES_ENABLE_CURSORS: "true"
    networks:
      - internal


volumes:
  uploads:
  crowdsec-db:

networks:
  internal:
    driver: bridge
